from __future__ import annotations

ROLLOUT_STATES = {
    "IDLE",
    "CANDIDATE_READY",
    "OFFLINE_GATES_PASSED",
    "PAPER_SOAK",
    "TESTNET_SOAK",
    "PENDING_LIVE_APPROVAL",
    "LIVE_SHADOW",
    "LIVE_CANARY_05",
    "LIVE_CANARY_15",
    "LIVE_CANARY_35",
    "LIVE_CANARY_60",
    "LIVE_STABLE_100",
    "ABORTED",
    "ROLLED_BACK",
    "COMPLETED",
}


TERMINAL_STATES = {"ABORTED", "ROLLED_BACK", "COMPLETED"}


ALLOWED_TRANSITIONS: dict[str, set[str]] = {
    "IDLE": {"CANDIDATE_READY"},
    "CANDIDATE_READY": {"OFFLINE_GATES_PASSED", "ABORTED", "ROLLED_BACK"},
    "OFFLINE_GATES_PASSED": {"PAPER_SOAK", "ABORTED", "ROLLED_BACK"},
    "PAPER_SOAK": {"TESTNET_SOAK", "ABORTED", "ROLLED_BACK"},
    "TESTNET_SOAK": {"PENDING_LIVE_APPROVAL", "ABORTED", "ROLLED_BACK"},
    "PENDING_LIVE_APPROVAL": {"LIVE_SHADOW", "LIVE_STABLE_100", "ABORTED", "ROLLED_BACK"},
    "LIVE_SHADOW": {"LIVE_CANARY_05", "ABORTED", "ROLLED_BACK"},
    "LIVE_CANARY_05": {"LIVE_CANARY_15", "ABORTED", "ROLLED_BACK"},
    "LIVE_CANARY_15": {"LIVE_CANARY_35", "ABORTED", "ROLLED_BACK"},
    "LIVE_CANARY_35": {"LIVE_CANARY_60", "ABORTED", "ROLLED_BACK"},
    "LIVE_CANARY_60": {"LIVE_STABLE_100", "ABORTED", "ROLLED_BACK"},
    "LIVE_STABLE_100": {"COMPLETED", "ROLLED_BACK"},
    "ABORTED": {"ROLLED_BACK", "IDLE"},
    "ROLLED_BACK": {"IDLE"},
    "COMPLETED": {"IDLE"},
}


PHASE_STATE_BY_NAME = {
    "shadow": "LIVE_SHADOW",
    "canary05": "LIVE_CANARY_05",
    "canary15": "LIVE_CANARY_15",
    "canary35": "LIVE_CANARY_35",
    "canary60": "LIVE_CANARY_60",
    "stable": "LIVE_STABLE_100",
}
